## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 43.0.0

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-7
    volumes: &appvolumes
      - ./src:/var/www/html
      - sockdata:/sock
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - traefik.docker.network=proxy
      - "traefik.http.routers.magento.rule=Host(`magento.giuseppe.best`) || Host(`magento.fumarola.ovh`)"
      - "traefik.http.routers.magento.entrypoints=websecure"
      - "traefik.http.services.magento.loadbalancer.server.port=8443"
      - "traefik.http.services.magento.loadbalancer.server.scheme=https"
      - "traefik.http.routers.magento.service=magento"
      - "traefik.http.routers.magento.tls.certresolver=lets-encrypt"
    #extra_hosts: &appextrahosts
      ## Selenium support, replace "magento.test" with URL of your site
      #- "magento.test:172.17.0.1"

  phpfpm:
    image: markoshust/magento-php:8.1-fpm-1
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts

  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    env_file: env/db.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  redis:
    image: redis:6.2-alpine

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.16-0
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.9-0
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher

  

  ## Blackfire support, uncomment to enable
  #blackfire:
  #  image: blackfire/blackfire:2
  #  ports:
  #    - "8307"
  #  env_file: env/blackfire.env

  ## Selenium support, uncomment to enable
  #selenium:
  #  image: selenium/standalone-chrome-debug:3.8.1
  #  ports:
  #    - "5900:5900"
  #  extra_hosts: *appextrahosts

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:

networks:
  proxy:
    external: true
