name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -azr --exclude=".git"
        rsh: cd /home/ubuntu/sites/magento2 && docker-compose up -d && bin/root chown app:app . -R && bin/composer install && bin/magento setup:upgrade && bin/magento deploy:mode:set production && bin/magento maintenance:disable
        path: ./
        remote_path: /home/ubuntu/sites/magento2
        remote_host: 129.152.11.153
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}

