name: Copia file da GitHub alla VPS e build del progetto

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Zip folder
        run: zip -r folder.zip /
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: folder
          path: folder.zip
      - name: Sync artifact with server
        run: |
          wget https://github.com/$GITHUB_REPOSITORY/download/main/folder.zip
          unzip folder.zip
          rsync -avz folder/ ubuntu@129.152.11.153:/home/ubuntu/sites/magento2
          rm -rf folder/ folder.zip
  build_project:
    needs: copy_files
    runs-on: ubuntu-latest
    steps:
      - name: Accedi alla VPS
        run: ssh -i ssh_private_key ubuntu@129.152.11.153
      - name: Esegui comandi di build del progetto sulla VPS
        run: |
          cd /home/ubuntu/sites/magento2
          bin/start --no-dev
          bin/copytocontainer --all
          bin/clinotty composer install
          bin/clinotty bin/magento setup:upgrade
          bin/clinotty bin/magento deploy:mode:set production
          bin/clinotty bin/magento indexer:reindex
          bin/clinotty bin/magento maintenance:disable
