name: Copia file da GitHub alla VPS e build del progetto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set SSH config
        run: |
          echo -e "Host *\n  StrictHostKeyChecking no" > ~/.ssh/config
      - name: Sync folder with server
        run: rsync -avz --exclude=.git --exclude=.github . ubuntu@129.152.11.153:/home/ubuntu/sites/magento2
      - name: Build project on server
        run: ssh ubuntu@129.152.11.153 'cd /home/ubuntu/sites/magento2 && /home/ubuntu/sites/magento2/build.sh'
