name: DEPLOY
on:
  push:
    branches:
    - main

jobs:

  # permission:
  #   name: permission
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using ssh key
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: "129.152.11.153"
  #       username: "ubuntu"
  #       key: ${{ secrets.DEPLOY_KEY }}
  #       port: "22"
  #       script: |
  #         cd /home/ubuntu/sites/magento2
  #         sudo chmod 777 ./ -R
  
  deploy:
    runs-on: ubuntu-latest
    # needs: permission
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -azr --exclude=".git"
        path: ./
        remote_path: /home/ubuntu/sites/magento2
        remote_host: 129.152.11.153
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}

  build:
    name: Build
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: "129.152.11.153"
        username: "ubuntu"
        key: ${{ secrets.DEPLOY_KEY }}
        port: "22"
        script: |
          cd /home/ubuntu/sites/magento2
          docker-compose up -d
          bin/composer install
          bin/magento setup:upgrade
          bin/magento deploy:mode:set production
          bin/magento maintenance:disable
