name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude=".git"
        path: ./
        remote_path: /home/ubuntu/sites/magento2
        remote_host: 129.152.11.153
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}

