name: Copia file da GitHub alla VPS e build del progetto

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Sync folder with server
        run: rsync -avz . ubuntu@129.152.11.153:/home/ubuntu/sites/magento2
  build_project:
    needs: copy_files
    runs-on: ubuntu-latest
    steps:
      - name: Accedi alla VPS
        run: ssh -i ssh_private_key ubuntu@129.152.11.153
      - name: Esegui comandi di build del progetto sulla VPS
        run: |
          cd /home/ubuntu/sites/magento2
          bin/start --no-dev
          bin/copytocontainer --all
          bin/clinotty composer install
          bin/clinotty bin/magento setup:upgrade
          bin/clinotty bin/magento deploy:mode:set production
          bin/clinotty bin/magento indexer:reindex
          bin/clinotty bin/magento maintenance:disable
