name: Copia file da GitHub alla VPS e build del progetto

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Crea il file della chiave privata
        run: |
          touch myfile
          chmod 600 myfile
          echo $SSH_PRIVATE_KEY > myfile
          cat myfile
      - name: Copia file da GitHub alla VPS
        run: rsync -avz -e "ssh -i ~/.ssh/id_rsa" * ubuntu@129.152.11.153:/home/ubuntu/sites/magento2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
  build_project:
    needs: copy_files
    runs-on: ubuntu-latest
    steps:
      - name: Accedi alla VPS
        run: ssh -i ssh_private_key ubuntu@129.152.11.153
      - name: Esegui comandi di build del progetto sulla VPS
        run: |
          cd /home/ubuntu/sites/magento2
          bin/start --no-dev
          bin/copytocontainer --all
          bin/clinotty composer install
          bin/clinotty bin/magento setup:upgrade
          bin/clinotty bin/magento deploy:mode:set production
          bin/clinotty bin/magento indexer:reindex
          bin/clinotty bin/magento maintenance:disable
